apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-api
  namespace: todo-api
  labels:
    app: todo-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-api
  template:
    metadata:
      labels:
        app: todo-api
    spec:
      containers:
        - name: todo-api
          image: flanaext.azurecr.io/todo-api:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: todo-api
  namespace: todo-api
spec:
  selector:
    app: todo-api
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
